name: flight_tracker
description: An app to check the status of flights
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  http: ^1.1.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  auto_size_text: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  auto_route: ^7.7.0
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0                 
  auto_route_generator: ^7.2.0               
  build_runner:       
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/json/
    - assets/img/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
 
flutter_native_splash:
  color: "#1565C0"
  image: assets/img/logo.png
  branding_mode: bottomRight
  web: false
